FROM python:3.9.15-alpine3.16
ADD . /code
WORKDIR /code
ENV FLASK_APP=app.py
ENV FLAKS_RUN_HOST=0.0.0.0
RUN pip install -r requirements.txt
RUN pip install Flask==2.0.3
RUN pip install Jinja2==3.1.1
#CMD ["python", "app.py"]
