ntp_timezone: Europe/Stockholm

firewall_allowed_tcp_ports:
  - "22"
  - "3000"
firewall_allowed_udp_ports: []

gitea_fqdn: 'git.example.com'
gitea_root_url: 'https://git.example.com'
gitea_protocol: http
gitea_start_ssh: true
gitea_db_host: 'mysql:3306'
gitea_db_type: mysql
gitea_db_name: gitea
gitea_db_user: gitea
gitea_db_password: gitea
